Traceback (most recent call last):
  File "/ei/.project-scratch/c/c3109f4b-0db1-43ec-8cb5-df48d8ea89d0/repos/Soy_expression_prediction/model_interpretation/motif_binomial_enrichment.py", line 3, in <module>
    from scipy.stats import binom_test
ImportError: cannot import name 'binom_test' from 'scipy.stats' (/hpc-home/mahony/.local/lib/python3.12/site-packages/scipy/stats/__init__.py). Did you mean: 'binomtest'?
